spring.datasource.url=${jdbc:mysql://mysql-134f0632-vijethakanagaraj-cdc2.k.aivencloud.com:20384/defaultdb?sslMode=REQUIRED&serverTimezone=UTC}

spring.datasource.username=${avnadmin}
spring.datasource.password=${AVNS_Zi8rQIB6H0YQ5-8LByh}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
